### ISSUE TITLE
Error on frontend

### ISSUE THREAD

**Issue by pwpdev** [wbcomdesigns/buddypress-check-in#2]
When select "Auto complete" showing error- https://prnt.sc/ftvkwt#_=_ .

Notice: Undefined index: place_types in /hermes/walnaweb08a/b1876/as.vapwbcom/brindlein/adarsh/wp-content/plugins/buddypress-check-in-master/includes/bpchk-filters.php on line 136

**Comment by pallavigdev** [comment]
this issue is fixed now.
