### ISSUE TITLE
Error in backend

### ISSUE THREAD

**Issue by pwpdev** [wbcomdesigns/buddypress-check-in#3]
Showing error on top in backend - https://prnt.sc/ftvm5h#_=_ .

Notice: Undefined index: google_place_types in /hermes/walnaweb08a/b1876/as.vapwbcom/brindlein/adarsh/wp-content/plugins/buddypress-check-in-master/admin/bpchk-admin-options-page.php on line 30 Notice: Undefined index: place_types in /hermes/walnaweb08a/b1876/as.vapwbcom/brindlein/adarsh/wp-content/plugins/buddypress-check-in-master/admin/bpchk-admin-options-page.php on line 70

**Comment by pallavigdev** [comment]
this error is fixed now.
